spring:
  application:
    name: movie-fun-app

  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

s3:
  accessKey: <access key id>
  secretKey: <secret access key>
  bucketName: <name of the bucket>

albums:
  url: //album-service/albums
movies:
  url: //movie-service/movies

# To expose actuator endpoints - NOT FOR PRODUCTION USE
management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,circuitbreakers
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
    hystrix:
      enabled: false
